import type { SystemDefinition } from "./types";

export const systems: SystemDefinition[] = [
  {
    id: "c64",
    name: "Commodore 64",
    era: "1982",
    core: "vice_x64sc",
    extensions: ["prg", "d64", "t64", "tap", "crt"],
    threads: false,
    description: "VICE x64sc; keyboard, joystick, tape, disk, and cartridge media.",
    fixture: {
      file: "happyflappy.prg",
      title: "Happy Flappy",
      source: "https://raw.githubusercontent.com/retrobrews/c64-games/master/happyflappy.prg",
      sha256: "bb269e813f0fc648c643b0fc3bbbc9e47a2e342ce144ff73191d1ee3068ed41e",
      bundled: false,
    },
  },
  {
    id: "atari2600",
    name: "Atari 2600",
    era: "1977",
    core: "stella2014",
    extensions: ["a26", "bin"],
    threads: false,
    description: "Stella 2014; a compact baseline for touch controls and WebGL rendering.",
    fixture: {
      file: "flappy_the_duck.bin",
      title: "Flappy the Duck",
      source: "https://raw.githubusercontent.com/retrobrews/atari2600-games/master/flappy_the_duck.bin",
      sha256: "e6b0e6db04d459a12e3202d695ce015fe8f84a0e67f7d26c87cc086ab500cab0",
      bundled: false,
    },
  },
  {
    id: "nes",
    name: "NES / Famicom",
    era: "1983",
    core: "fceumm",
    extensions: ["nes", "unf", "unif", "fds"],
    threads: false,
    description: "FCEUmm; mature 8-bit console emulation with virtual and physical controllers.",
    fixture: {
      file: "240pee.nes",
      title: "240p Test Suite (NES)",
      source: "https://raw.githubusercontent.com/christopherpow/nes-test-roms/master/240pee/240pee.nes",
      sha256: "228a370b32daacec4c95927aa18243a57be2d45d1d038479ba9d4bb19d05985e",
      bundled: true,
    },
  },
  {
    id: "snes",
    name: "SNES / Super Famicom",
    era: "1990",
    core: "snes9x",
    extensions: ["sfc", "smc", "fig", "swc"],
    threads: false,
    description: "Snes9x; representative 16-bit rendering, audio, and multitap-capable input.",
    fixture: {
      file: "blt.sfc",
      title: "BLT",
      source: "https://raw.githubusercontent.com/retrobrews/snes-games/master/blt.sfc",
      sha256: "1f4004deb5981fa6115c1d3676add48d5437a3edb52a9203fbe14085fcb0b7ac",
      bundled: false,
    },
  },
  {
    id: "genesis",
    name: "Genesis / Mega Drive",
    era: "1988",
    core: "genesis_plus_gx",
    extensions: ["md", "gen", "bin", "smd"],
    threads: false,
    description: "Genesis Plus GX; 16-bit Sega hardware with mature libretro compatibility.",
    fixture: {
      file: "megaflappysis.bin",
      title: "Mega Flappy Sis",
      source: "https://raw.githubusercontent.com/retrobrews/md-games/master/megaflappysis.bin",
      sha256: "7e428be1f4a337abd86ab35db9b10c755efb14aad7f62f701369481dd2d6357f",
      bundled: false,
    },
  },
  {
    id: "gba",
    name: "Game Boy Advance",
    era: "2001",
    core: "mgba",
    extensions: ["gba"],
    threads: false,
    description: "mGBA; handheld emulation with save memory, audio, and touch controls.",
    fixture: {
      file: "240p-test-suite.gba",
      title: "240p Test Suite (GBA)",
      source: "https://raw.githubusercontent.com/mechanize-work/gba-eval/main/corpus/roms/test/misc/240p-test-suite.gba",
      sha256: "47844f7140738a06f8f3bc09780da3ab095539a250b870f614feed561d9d6f34",
      bundled: true,
    },
  },
  {
    id: "arcade",
    name: "Arcade / MAME 2003-Plus",
    era: "1970s–1990s",
    core: "mame2003_plus",
    extensions: ["zip"],
    threads: false,
    description: "MAME 2003-Plus; selected-driver arcade emulation with cabinet-style controls.",
    fixture: {
      file: "circus.zip",
      title: "Circus (Exidy, 1977)",
      source: "https://www.mamedev.org/roms/circus/circus.zip",
      sha256: "27d3952dba171d50ef63a7a651e063f83830d2e07e4799dadcc5c42e0371d424",
      bundled: false,
    },
    notes: "The official MAME download permits local non-commercial testing but not rebundling, so this fixture is only fetched by the explicit local-fixture command.",
  },
  {
    id: "dos",
    name: "DOS PC",
    era: "1981–2000",
    core: "dosbox_pure",
    extensions: ["zip", "dosz", "iso", "cue"],
    threads: true,
    description: "DOSBox Pure; threaded x86 emulation and DOS audio in a cross-origin-isolated page.",
    fixture: {
      file: "dos-lab.zip",
      title: "DOS Lab VGA Demo",
      source: "fixtures-src/dos-lab.asm",
      sha256: "75e719b7396b7fb54d7ffb442ccf7220d4e5cd9db938e6850e138a97e214f7f2",
      bundled: true,
    },
  },
  {
    id: "ps1",
    name: "PlayStation",
    era: "1994",
    core: "pcsx_rearmed",
    extensions: ["cue", "chd", "pbp", "iso", "exe"],
    threads: false,
    description: "PCSX-ReARMed; the high-end production-tier latency and throughput proof.",
    fixture: {
      file: "TETRADE_PSX.cue",
      title: "Tetrade",
      source: "https://github.com/Logan-Campbell/Tetrade/releases/download/v1.0/TETRADE_PSX.cue",
      sha256: "98cb45d15241900c8459176e833be5edee78120763ac4d91d79d24020b10d67a",
      bundled: true,
    },
    notes: "Tetrade is an MIT-licensed PS1 homebrew game. The CUE launches its adjacent BIN track, and PCSX-ReARMed uses its HLE BIOS.",
  },
];

export const systemById = new Map(systems.map((system) => [system.id, system]));
